services:
  - type: web
    name: quicktutor-ghana
    env: node
    buildCommand: npm install && npm install --prefix backend && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: VITE_PAYSTACK_PUBLIC_KEY
        sync: false
      - key: ARKESEL_API_KEY
        sync: false
      - key: VITE_BACKEND_URL
        sync: false

